version: '3.8'

services:
  ms-sql-server:
    image:  mcr.microsoft.com/mssql/server:2017-latest-ubuntu

    ports:
      - "4454:1433"
    
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2022"
      MSSQL_PID: Express
      

  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
      
    environment:
      - DBHOST=ms-sql-server
      - DBPORT=1433
      - DBUSER=SA
      - DBPASSWORD=Pa55w0rd2022
      - DBNAME=MyBookStore

    ports:
      - "8888:80"
      
    restart: always
     
